config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts

  resources :votes, only: [] do
    member do
      post :upvote
      post :downvote
    end
  end

  resources :bookmarks, only: [:index, :create] do
    collection do
      delete :destroy
    end
  end

  resource :search,  only: [:create] do
    collection do
      get :tags, path: '/tags/:tag'
    end
  end

  resource :profile, only: [:new, :show, :edit, :update]

  root 'posts#index'

  get '/:username', to: 'profiles#public_profile'
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

  attr_accessor :name, :username, :avatar

  def update_user!(user_params)
    params =  user_params.extract!(:name, :username, :avatar)
    user.name = params[:name]
    user.username = params[:username]
    user.avatar   = params[:avatar]
    user.save
  end

  def set_attributes!
    self.name     = user.name
    self.username = user.username
    self.avatar   = user.avatar
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!, except: [:public_profile]
  before_action :load_profile, only: [:show, :edit, :update]

  def show
    @profile = current_user.profile
    @profile.set_attributes! if @profile.present?
  end

  def public_profile
    @user    = User.find_by_username(params[:username]) || User.find_by_id(params[:username])
    @profile = @user.profile
  end

  def edit
    @profile = current_user.profile

    if @profile.blank?
      @profile = current_user.build_profile
      @profile.save
    else
      @profile.set_attributes!
    end
  end

  def update
    @profile = current_user.profile
    @profile.update_user!(profile_params)

    if @profile.update_attributes(profile_params)
      @notice = 'Profile updated successfully'
    end

    render action: :edit, notice: @notice
  end

  private

  def load_profile
    @profile = current_user.profile
  end

  def profile_params
    params.require(:profile).permit(:name, :avatar, :username, :phone_no, :dob,
      :place, :country)
  end

end

app/views/profiles/_form.html.slim
= form_for @profile, role: 'form', html: { class: 'profile-edit' } do |f|

  .form-group
    = f.label :avatar, 'Proile pic'
    = f.file_field :avatar

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', placeholder: 'Deepak Kumar'

  .form-group
    = f.label :username
    = f.text_field :username, class: 'form-control', placeholder: 'deepakkumar06'

  .form-group
    = f.label :phone_no
    = f.text_field :phone_no, class: 'form-control', placeholder: 'eg: +91-9495821948'

  .form-group
    = f.label :dob
    = f.date_select :dob, class: 'form-control'

  .form-group
    = f.label :place
    = f.text_field :place, class: 'form-control', placeholder: 'eg: New Delhi'

  .form-group
    = f.label :country
    = f.text_field :country, class: 'form-control', placeholder: 'eg: India'

  .form-group
    = f.submit 'Save', class: 'btn btn-default'
    = link_to 'Cancel', profile_path, class: 'link-back'

app/views/profiles/edit.html.slim
.row
  .col-md-6
    = render 'form'

app/views/profiles/public_profile.html.slim
.row
  .col-md-6
    p= image_tag(@user.avatar.thumb.url, class: 'image-rounded image-avatar')
    p= @user.name
    p= "@#{@user.username}"
    p= @profile.place
    p= @profile.country
    p
      label Posts
      label= @user.posts.count
    p
      label Bookmarks
      label 10

app/views/profiles/show.html.slim
.row
  .col-md-6
    = link_to edit_profile_path, class: 'action' do
      i.ion-edit
      span Edit profile