config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts

  resources :votes, only: [] do
    member do
      post :upvote
      post :downvote
    end
  end

  resources :bookmarks, only: [:index, :create] do
    collection do
      delete :destroy
    end
  end

  resource :search,  only: [:create] do
    collection do
      get :tags, path: '/tags/:tag'
    end
  end

  resource :profile, only: [:new, :show, :edit, :update]

  root 'posts#index'

  get '/:username', to: 'profiles#public_profile'
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :replies, foreign_key: :reply_to

  attr_accessor :tag_string

  scope :all_posts, -> {  where(reply_to: nil) }

  def set_tags!(args)
    str = args[:tag_string]
    return if str.strip.empty?
    self.tags = str.squish.split(/\s|,/)
  end

  def set_tag_string!
    self.tag_string = tags.join(' ')
  end

  def upvote!
    update_attribute(:upvote, self.upvote + 1)
  end

  def downvote!
    update_attribute(:downvote, self.downvote + 1)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all_posts
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @reply   = Post.new(reply_to: @post.id)
    @replies = @post.replies
  end

  # GET /posts/new
  def new
    @post = current_user.posts.new
  end

  # GET /posts/1/edit
  def edit
    @post.set_tag_string!
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_create_params)
    @post.set_tags!(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @post.set_tags!(post_params)

    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_create_params
      post_params.merge(params.require(:post).permit(:reply_to))
    end

    def post_params
      params.require(:post).permit(:content, :tag_string)
    end

end

app/views/posts/_form.html.slim
= form_for(@post) do |f|
  - if @post.errors.any?
    .error-report
      p
        = pluralize(@post.errors.count, "error")
        | prohibited this @post from being saved

      ul
        - @post.errors.full_messages.each do |message|
          li= message

  = f.hidden_field :reply_to

  .form-group
    = f.label :content
    = f.text_area :content, class: 'form-control'

  .form-group
    = f.label :tag_string, 'tags'
    = f.text_field :tag_string, class: 'form-control'

  .form-group
    = f.submit 'Post', class: 'btn btn-default'

app/views/posts/_post.html.slim
li.list-group-item.post-item
  .post-header
    span.posted-by
      = link_to h_name(post.user), h_profile_path(post.user)
    span.posted-time
      = time_ago_in_words(post.created_at)
    .dropdown.pull-right
      button#post-item-dropdown.btn.btn-default.btn-xs.dropdown-toggle aria-expanded='true' data-toggle='dropdown'
        span.caret
      ul.dropdown-menu aria-labelledby='post-item-dropdown' role='menu'
        li role='presentation'
          = link_to 'Share', '#', role: 'menuitem'

        li role='presentation'
          = link_to 'Edit', edit_post_path(post), role: 'menuitem'

        li role='presentation'
          = link_to 'Delete', post_path(post), method: :delete, role: 'menuitem'

        li role='presentation'
          = link_to 'Report', '#', method: :delete, role: 'menuitem'

  .post-content= h_render(post.content)
  .post-meta
    span.tags= h_list_tags(post.tags)
  .post-footer
    = render 'posts/post_footer', post: post

app/views/posts/_post_footer.html.slim
span.comment
  = link_to h_reply_count(post), '#',
    class: 'btn btn-default btn-xs'

  - if policy(post).already_bookmarked?
    = link_to 'Bookmark', bookmarks_path(post_id: post),
      class: 'btn btn-default btn-xs remove-bookmark',
      method: :delete,
      remote: true
  - else
    = link_to 'Bookmark', bookmarks_path(post_id: post),
      class: 'btn btn-default btn-xs add-bookmark',
      method: :post,
      remote: true

span.pull-right.post-actions
  = link_to upvote_vote_path(post), title: 'Upvote',
    class: "btn btn-default btn-xs upvote #{'disabled' unless policy(post).upvote?}",
    method: :post,
    remote: true do
    i.ion-thumbsup
    | &nbsp;Upvote

  = link_to downvote_vote_path(post), title: 'Downvote',
    class: "btn btn-default btn-xs downvote #{'disabled' unless policy(post).downvote?}",
    method: :post,
    remote: true do
    i.ion-thumbsdown
    | &nbsp;Downvote

app/views/posts/_posts.html.slim
ul.list-group
  - posts.each do |post|
    = render 'posts/post', post: post

app/views/posts/edit.html.slim
.row
  .col-md-8
    h2 Edit post

    = render 'form'

    = link_to 'Back', posts_path

app/views/posts/index.html.slim
.row
  .col-md-8
    = render 'posts', posts: @posts

app/views/posts/new.html.slim
.row
  .col-md-8
    h2 Write new post
    = render 'form', post: @post
    = link_to 'Cancel', posts_path

app/views/posts/show.html.slim
.row
  .col-md-8
    ul.list-group
      = render 'post', post: @post

    h2 Reply
    = render 'form', post: @reply
    = render 'posts', posts: @replies